version: "3"
services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v19.2.5
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: always
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    container_name: nakama
    image: heroiclabs/nakama:2.11.1
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "1m"
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        exec /nakama/nakama --config /nakama/data/config.yml
    restart: always
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
    volumes:
      - ./nakama/data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  client:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nakama/nginx.conf:/etc/nginx/nginx.conf
      - ./nakama/apache.htpasswd:/etc/nginx/.htpasswd
      - ./nakama/website:/usr/share/nginx/html
volumes:
  data:
