[package]
name = "omgd"
version = "0.1.0"
authors = ["Anand Mallik <amallik@newnoiseworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
convert_case = "0.4.0"
