version: "2"
services:
  app:
    build: .
    volumes:
      - ./:/go/src/github.com/newnoiseworks/tpl-fred
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
    working_dir: /go/src/github.com/newnoiseworks/tpl-fred

  dev:
    extends:
      service: app
    command: zsh

  build-osx:
    extends:
      service: app
    command: env GOOS=darwin GOARCH=amd64 go build -o tpl-fred.osx github.com/newnoiseworks/tpl-fred

  build-windows:
    extends:
      service: app
    command: env GOOS=windows GOARCH=amd64 go build -o tpl-fred.exe github.com/newnoiseworks/tpl-fred
