version: "2"
services:
  godot-builder:
    build:
      context: .build/GodotDockerfile
      dockerfile: Dockerfile
    image: newnoiseworks/godot-builder

  build-root:
    build: .
    volumes:
      - ./dist:/root/game/dist
    working_dir: /root/game/
    environment:
      - BUILD_ENV=${BUILD_ENV}

  dev:
    depends_on:
      - godot-builder
    extends:
      service: build-root
    command: bash

  build-mac:
    depends_on:
      - godot-builder
    extends:
      service: build-root
    command: /bin/bash .build/mac.sh
    image: newnoiseworks/game-build-mac-${BUILD_ENV}

  build-windows:
    depends_on:
      - godot-builder
    extends:
      service: build-root
    command: /bin/bash .build/windows.sh
    image: newnoiseworks/game-build-windows-${BUILD_ENV}

  build-web:
    depends_on:
      - godot-builder
    extends:
      service: build-root
    command: /bin/bash .build/web.sh
    image: newnoiseworks/game-build-web-${BUILD_ENV}

  build-x11:
    depends_on:
      - godot-builder
    extends:
      service: build-root
    command: /bin/bash .build/x11.sh
    image: newnoiseworks/game-build-x11-${BUILD_ENV}
