omgd:
  deploy:
    server:
      gcloud:
        project: project-name
        zone: us-east4-c
    game:
      itchio:
        project: project-name
        user: itch-user

####
game:
  version: staging
    
