version: "2"
services:
  build-root:
    build: .
    volumes:
      - ./:/root/game/
    working_dir: /root/game/
    environment:
      - BUILD_ENV=${BUILD_ENV}

  dev:
    extends:
      service: build-root
    command: bash

  build-mac:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/mac-${BUILD_ENV} && godot -v --export 'Mac OSX' dist/mac-${BUILD_ENV}/game-${BUILD_ENV}.zip"

  build-windows:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/windows-${BUILD_ENV} && godot -v --export 'Windows Desktop' dist/windows-${BUILD_ENV}/game-${BUILD_ENV}.exe"

  build-web:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/web-${BUILD_ENV} && godot -v --export 'HTML5' dist/web-${BUILD_ENV}/index.html"

  build-x11:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/x11-${BUILD_ENV} && godot -v --export 'Linux/X11' dist/x11-${BUILD_ENV}/game-${BUILD_ENV}.x86_64"
