name: mainpush

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  versionbump:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true 
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
  release-build:
    needs: versionbump
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
            linux,
            windows
        ]

        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/omgd
            asset_name: omgd
          - name: windows
            os: windows-latest
            artifact_name: target/release/omgd.exe
            asset_name: omgd-windows

    steps:
    - uses: actions/checkout@v1

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: cargo build --release --locked

  upload-release:
    needs: release-build
    name: Publish latest release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "latest"
        files: |
          target/release/omgd
          target/release/omgd.exe
